site_name: Dhanman

nav:
  - Home: index.md
  - Accounting: accounting\introduction.md
  - Authentication: authentication-authorization.md
  - Sytem Architecture:
      - Architecture: system_overview/architecture.md
      - Sales: system_overview/dhanman_sales.md
      - Overview: system_overview/design.md
      - Budgeting: system_overview/budgeting_system.md
      - Water Tanker: system_overview/water_tanker.md
      - RabbitMQ Setup: system_overview/rabbitmq_setup.md
      - Messging Overview: system_overview/messging_design.md
      - MinIO Setup: system_overview/MinIO.md
      - MKDocs: system_overview/mkdocs.md
      - Commands: system_overview/services_commands.md
      - dbtula-command: dbtula/DbTula-Extract-Commands.md
  - Test:
      - Playwright E2E: test/testid-strategy.md
  - Permissions:
      - Naming Guidelines: permissions/permissions-naming-guidelines.md
      - Common: system_overview/common.md
      - Sales: permissions/sales.md
  - Accounting Entries:
      - Purchase Transactions: accounting_entries/purchase_transactions.md
      - Sales Transactions: accounting_entries/sales_transactions.md
      - Payroll Transactions: accounting_entries/payroll_transactions.md
      - Other Entries: accounting_entries/entries_others.md
      - Sample Entries: accounting_entries/entries_samples.md
  - Financial Reports:
      - Ledger of Customers: financial_reports/ledger_of_customers.md
      - Ledger of Vendors: financial_reports/ledger_of_vendors.md
      - Trial Balance: financial_reports/trial_balance.md
      - Balance Sheet: financial_reports/balance_sheet.md
      - Profit and Loss Statement: financial_reports/profit_and_loss_statement.md
      - Cash Flow Statement: financial_reports/cash_flow_statement.md
      - Accounts Receivable Aging Report: financial_reports/accounts_receivable_aging_report.md
      - Accounts Payable Aging Report: financial_reports/accounts _payable_aging_report.md
      - Pending Dues Report: financial_reports/pending_dues_report.md
  - Payroll:
      - Sample Templates: payroll/sample_templates.md
  - Office Etiquette Policy: policies/office_etiquette_policy.md
  - Coding Conventions:
      - Backend: coding_conventions/cc_principle_backend.md
  - How Tos:
      - Email Templates: how-to/email_templates.md
      - App UI Structure: how-to/app-ui-structure.md
  - Devops:
      - DigitalOcen: devops/qa_deployment_guide.md
      - Data Backup: devops/dump_restore_clean.md
      - QA-PROD: devops/qa_prod_deployment_guide.md
  - About: about.md

theme:
  name: "material"
  highlightjs: true
  logo: images/dhanman-docs.png
  favicon: images/dhanman-docs.png

markdown_extensions:
  - codehilite:
      guess_lang: false
  - admonition
  - toc:
      permalink: true
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.3.1/highlight.min.js
  - js/extra.js
  - https://cdn.jsdelivr.net/npm/glightbox/dist/js/glightbox.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.3.1/styles/default.min.css
  - extra.css
  - https://cdn.jsdelivr.net/npm/glightbox/dist/css/glightbox.min.css
