site_name: DhanMan

nav:
  - Home: index.md
  - Accounting: accounting\introduction.md
  - Authentication: authentication-authorization.md
  - Permissions: 
      - Common: permissions\common.md
      - Sales: permissions\sales.md
  - Accounting Entries:
      - Purchase Transactions: accounting_entries/purchase_transactions.md
      - Sales Transactions: accounting_entries/sales_transactions.md
      - Payroll Transactions: accounting_entries/payroll_transactions.md
      - Other Entries: accounting_entries/entries_others.md
      - Sample Entries: accounting_entries/entries_samples.md
  - Financial Reports:
      - Ledger of Customers: financial_reports/ledger_of_customers.md
      - Ledger of Vendors: financial_reports/ledger_of_vendors.md
      - Trial Balance: financial_reports/trial_balance.md
      - Balance Sheet: financial_reports/balance_sheet.md
      - Profit and Loss Statement: financial_reports/profit_and_loss_statement.md
      - Cash Flow Statement: financial_reports/cash_flow_statement.md
      - Accounts Receivable Aging Report: financial_reports/accounts_receivable_aging_report.md
      - Accounts Payable Aging Report: financial_reports/accounts _payable_aging_report.md
      - Pending Dues Report: financial_reports/pending_dues_report.md
  - Payroll:
      - Sample Templates: payroll/sample_templates.md
  - Office Etiquette Policy: policies/office_etiquette_policy.md
  - Coding Conventions:
      - Backend: coding_conventions/cc_principle_backend.md
  - How Tos:
      - Email Templates: how-to/email-templates.md
  - Devops:
      - DigitalOcen: devops/qa_deployment_guide.md
      - QA-PROD: devops/qa_prod_deployment_guide.md
  - About: about.md

theme:
  name: "material"
  highlightjs: true

markdown_extensions:
  - codehilite:
      guess_lang: false
  - admonition
  - toc:
      permalink: true
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.3.1/highlight.min.js
  - js/extra.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.3.1/styles/default.min.css
  - extra.css
